---
abstract: 'Arbiter of the word card-based game Apples to Apples'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Applebot
no_index:
  directory:
    - inc
    - share
recommends:
  Net::Twitter: 0
requires:
  File::ShareDir: 0
  IO::All: 0
  Lingua::EN::Inflect: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  MooseX::AttributeHelpers: 0
  Roman: 0
  String::IRC: 0
  YAML: 0
resources:
  homepage: http://github.com/sartak/Bot-Applebot/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/Bot-Applebot.git
version: 0.01
